# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Extended semantic convention attributes for GenAI operations.
These attributes are not yet available in the standard opentelemetry-semantic-conventions package.
"""

from enum import Enum
from typing import Final

# Common attributes
GEN_AI_TOOL_DEFINITIONS: Final = "gen_ai.tool.definitions"
"""
The tool definitions used by the model.
"""

# Attributes present in the current upstream GenAI semantic conventions but
# not yet shipped by the minimum opentelemetry-semantic-conventions version
# supported by LoongSuite.
GEN_AI_PROMPT_NAME: Final = "gen_ai.prompt.name"
"""The name that uniquely identifies the prompt template."""

GEN_AI_PROMPT_VERSION: Final = "gen_ai.prompt.version"
"""The version of the prompt template."""

GEN_AI_PROMPT_VARIABLE_PREFIX: Final = "gen_ai.prompt.variable."
"""Prefix for prompt-template variables; append the variable name."""

GEN_AI_REQUEST_STREAM: Final = "gen_ai.request.stream"
"""Whether the request uses streaming. Emit only for streaming requests."""

GEN_AI_REQUEST_REASONING_LEVEL: Final = "gen_ai.request.reasoning.level"
"""The provider-specific reasoning or thinking effort requested."""

GEN_AI_RESPONSE_TIME_TO_FIRST_CHUNK: Final = (
    "gen_ai.response.time_to_first_chunk"
)
"""Time from request issuance to the first response chunk, in seconds."""

GEN_AI_USAGE_REASONING_OUTPUT_TOKENS: Final = (
    "gen_ai.usage.reasoning.output_tokens"
)
"""Output tokens used for reasoning, included in output-token usage."""

GEN_AI_CONVERSATION_COMPACTED: Final = "gen_ai.conversation.compacted"
"""Positive indicator that the effective conversation was compacted."""

GEN_AI_AGENT_VERSION: Final = "gen_ai.agent.version"
"""The version of the GenAI agent."""

GEN_AI_WORKFLOW_NAME: Final = "gen_ai.workflow.name"
"""The low-cardinality, human-readable name of the GenAI workflow."""

# Embedding attributes
GEN_AI_EMBEDDINGS_DIMENSION_COUNT: Final = "gen_ai.embeddings.dimension.count"
"""
The dimensionality of the embedding vectors generated by the model.
"""

# Tool call attributes
GEN_AI_TOOL_CALL_ARGUMENTS: Final = "gen_ai.tool.call.arguments"
"""
The arguments or parameters passed to the tool during invocation.
"""

GEN_AI_TOOL_CALL_RESULT: Final = "gen_ai.tool.call.result"
"""
The result returned by the tool after execution.
"""

# Retrieval attributes
GEN_AI_RETRIEVAL_QUERY_TEXT: Final = "gen_ai.retrieval.query.text"
"""
The retrieval query text (short phrase). Per upstream OpenTelemetry GenAI conventions.
"""

GEN_AI_RETRIEVAL_DOCUMENTS: Final = "gen_ai.retrieval.documents"
"""
The documents retrieved from the search or vector database.
"""

GEN_AI_RETRIEVAL_TOP_K: Final = "gen_ai.retrieval.top_k"
"""The maximum number of retrieval results requested."""

# Rerank attributes
GEN_AI_RERANK_DOCUMENTS_COUNT: Final = "gen_ai.rerank.documents.count"
"""
The number of documents provided as input to the reranking operation.
"""

GEN_AI_RERANK_SCORING_PROMPT: Final = "gen_ai.rerank.scoring_prompt"
"""
Custom scoring prompt used by LLM-based rerankers to evaluate document relevance.
"""

GEN_AI_RERANK_RETURN_DOCUMENTS: Final = "gen_ai.rerank.return_documents"
"""
Whether the reranker should return the full document content in the response.
"""

GEN_AI_RERANK_MAX_CHUNKS_PER_DOC: Final = "gen_ai.rerank.max_chunks_per_doc"
"""
Maximum number of chunks to consider per document during reranking.
"""

GEN_AI_RERANK_DEVICE: Final = "gen_ai.rerank.device"
"""
The computation device used for inference in model-based rerankers.
"""

GEN_AI_RERANK_BATCH_SIZE: Final = "gen_ai.rerank.batch_size"
"""
The batch size used for processing documents during reranking.
"""

GEN_AI_RERANK_MAX_LENGTH: Final = "gen_ai.rerank.max_length"
"""
Maximum sequence length for tokenization in the reranking model.
"""

GEN_AI_RERANK_NORMALIZE: Final = "gen_ai.rerank.normalize"
"""
Whether to normalize the relevance scores returned by the reranker.
"""

GEN_AI_RERANK_INPUT_DOCUMENTS: Final = "gen_ai.rerank.input_documents"
"""
The documents provided as input to the reranking operation.
"""

GEN_AI_RERANK_OUTPUT_DOCUMENTS: Final = "gen_ai.rerank.output_documents"
"""
The reranked documents returned by the reranking operation.
"""

# Skill attributes, refer to
# https://github.com/alibaba/loongsuite-semantic-conventions/pull/19
GEN_AI_SKILL_NAME: Final = "gen_ai.skill.name"
"""
The name of the GenAI skill being invoked.
"""

GEN_AI_SKILL_ID: Final = "gen_ai.skill.id"
"""
The unique identifier of the GenAI skill being invoked.
"""

GEN_AI_SKILL_DESCRIPTION: Final = "gen_ai.skill.description"
"""
Free-form description of the GenAI skill provided by the application.
"""

GEN_AI_SKILL_VERSION: Final = "gen_ai.skill.version"
"""
The version of the GenAI skill being invoked.
"""

GEN_AI_SPAN_KIND: Final = "gen_ai.span.kind"
"""
The semantic type of GenAI operation (e.g., LLM, AGENT, EMBEDDING).
This attribute extends OpenTelemetry semantics to classify GenAI-specific operations
for scenarios like Completion, Chat, RAG, Agent, and Tool execution.

Note: This is an Attribute, distinct from OpenTelemetry's Span kind field.
"""

GEN_AI_INPUT_MULTIMODAL_METADATA: Final = "gen_ai.input.multimodal_metadata"
"""
The multimodal metadata of the input messages.
"""

GEN_AI_OUTPUT_MULTIMODAL_METADATA: Final = "gen_ai.output.multimodal_metadata"
"""
The multimodal metadata of the output messages.
"""

GEN_AI_USAGE_TOTAL_TOKENS: Final = "gen_ai.usage.total_tokens"
"""
The total number of tokens used in the operation, calculated as the sum of input and output tokens.
This is the sum of gen_ai.usage.input_tokens and gen_ai.usage.output_tokens when both are available.
"""

GEN_AI_RESPONSE_TIME_TO_FIRST_TOKEN: Final = (
    "gen_ai.response.time_to_first_token"
)
"""
The time in nanoseconds from the request start to when the first token was received in a streaming response.
This metric is important for measuring the latency perceived by users in streaming scenarios.
"""

# Entry attributes (LoongSuite semantic conventions)
GEN_AI_SESSION_ID: Final = "gen_ai.session.id"
"""
The session ID for the AI application.
"""

GEN_AI_USER_ID: Final = "gen_ai.user.id"
"""
The C-end user identifier of the application.
"""

# ReAct Step attributes (LoongSuite semantic conventions)
GEN_AI_REACT_FINISH_REASON: Final = "gen_ai.react.finish_reason"
"""
The reason why this ReAct iteration ended.
"""

GEN_AI_REACT_ROUND: Final = "gen_ai.react.round"
"""
The round number of this ReAct iteration (1-based).
"""

GEN_AI_USAGE_CACHE_CREATION_INPUT_TOKENS: Final = (
    "gen_ai.usage.cache_creation.input_tokens"
)
"""
Tokens written to the model provider cache (subset of input usage).
"""

GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS: Final = (
    "gen_ai.usage.cache_read.input_tokens"
)
"""
Tokens read from the model provider cache (subset of input usage).
"""


class GenAiSpanKindValues(Enum):
    AGENT = "AGENT"
    """Agent operation (create_agent, invoke_agent)."""

    LLM = "LLM"
    """Large Language Model operation (chat completion)."""

    EMBEDDING = "EMBEDDING"
    """Embedding generation operation."""

    TOOL = "TOOL"
    """Tool execution operation."""

    WORKFLOW = "WORKFLOW"
    """GenAI workflow invocation operation."""

    MCP = "MCP"
    """Tool execution via Model Context Protocol."""

    RETRIEVER = "RETRIEVER"
    """Document retrieval operation."""

    RERANKER = "RERANKER"
    """Document reranking operation."""

    MEMORY = "MEMORY"
    """Memory operation."""

    ENTRY = "ENTRY"
    """Entry point for AI application system calls."""

    STEP = "STEP"
    """ReAct step (Reasoning-Acting iteration)."""


class GenAiExtendedOperationNameValues(Enum):
    INVOKE_WORKFLOW = "invoke_workflow"
    """Invoke a coordinated GenAI workflow."""

    PLAN = "plan"
    """Agent planning or task-decomposition phase."""

    RETRIEVAL = "retrieval"
    """Retrieval operation (vector store / database lookup) from upstream OpenTelemetry GenAI conventions."""

    RERANK_DOCUMENTS = "rerank_documents"
    """Rerank documents operation."""

    ENTER = "enter"
    """Entry operation for AI application system."""

    REACT = "react"
    """ReAct step operation (Reasoning-Acting iteration)."""


class GenAiExtendedProviderNameValues(Enum):
    DASHSCOPE = "dashscope"
    """DashScope."""

    OLLAMA = "ollama"
    """Ollama."""

    MOONSHOT = "moonshot_ai"
    """Moonshot."""
